name: Setup Rust
description: "Set up rust nightly"

inputs:
  components:
    description: "passed to actions-rust-lang/setup-rust-toolchain"
    default: ""
  cache:
    description: ""
    default: "true"
outputs:
  rust:
    description: setup rust output
    value: ${{ toJSON(steps.rust.outputs) }}
runs:
  using: composite
  steps:
    - id: rust
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      env:
        # renovate: datasource=rust-version depName=none
        RUST_VERSION: nightly-2026-04-29
      with:
        toolchain: ${{ env.RUST_VERSION }}
        cache-workspaces: './gatelogue-types-rs -> target'
        components: ${{ inputs.components }}
        cache: ${{ inputs.cache }}
