name: Setup Node
description: "Set up pnpm, node and cache pnpm"

inputs:
  cache:
    description: ""
    default: "true"
  registry-url:
    description: ""
outputs:
  pnpm:
    description: setup pnpm output
    value: ${{ toJSON(steps.pnpm.outputs) }}
  node:
    description: setup node output
    value: ${{ toJSON(steps.node.outputs) }}
  cache:
    description: setup cache output
    value: ${{ toJSON(steps.cache.outputs) }}
runs:
  using: composite
  steps:
    - id: pnpm
      uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
      with:
        version: "10.33.0"
    - id: node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "25.8.1"
        cache: ${{ (inputs.cache && 'pnpm') || 'none' }}
        cache-dependency-path: "**/pnpm-lock.yaml"
        registry-url: ${{ inputs.registry-url }}
    - id: cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      if: inputs.cache
      with:
        path: |
          ~/.local/share/pnpm
          **/node_modules
        key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
