repos:
  - repo: local
    hooks:
      - id: hatch-ruff
        name: hatch-ruff
        language: system
        entry: bash -c "cd gatelogue-aggregator && hatch fmt -f"
        pass_filenames: false
        verbose: true
      - id: prettier
        name: prettier
        language: system
        entry: bash -c "cd gatelogue-client && pnpm run format"
        pass_filenames: false
        verbose: true
      - id: cargo fmt
        name: cargo fmt
        entry: cargo +nightly fmt
        language: system
        types: [ rust ]
        pass_filenames: false
