name: Mise
description: Mise

inputs:
  envs:
    description: envs
    default: "lint,node,py,rs"
  cache:
    description: cache
    default: "true"

outputs:
  mise-action:
    description: mise-action output
    value: ${{ toJSON(steps.mise-action.outputs) }}
  cache-rust:
    description: rust cache output
    value: ${{ toJSON(steps.cache-rust.outputs) }}
  cache-node:
    description: node cache output
    value: ${{ toJSON(steps.cache-node.outputs) }}

runs:
  using: composite
  steps:
    - id: mise-env
      shell: bash
      run: echo "MISE_ENV=$ENVS" > "$GITHUB_ENV" # zizmor: ignore[github-env]
      env:
        ENVS: ${{ inputs.envs }}

    - id: mise-action
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        version: v2026.8.15
        cache: ${{ inputs.cache }}

    - id: cache-rust
      if: inputs.cache && contains(inputs.envs, 'rs')
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      with:
        workspaces: "./gatelogue-types-rs -> target"

    - if: contains(inputs.envs, 'rs')
      run: mise install rust --force
      shell: bash

    - id: cache-node
      if: inputs.cache && contains(inputs.envs, 'node')
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.local/share/pnpm
          **/node_modules
        key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
