allowBuilds:
  esbuild: true
  better-sqlite3: true
minimumReleaseAge: 4320
minimumReleaseAgeStrict: false
minimumReleaseAgeExclude:
  - '@_7d/eslint-formatter-sarif@1.0.1'
packages:
  - '../gatelogue-types-ts/'
sharedWorkspaceLockfile: false
