name: Setup Python
description: "Set up uv and hatch"

inputs:
  cache:
    description: ""
    default: "true"

outputs:
  uv:
    description: setup uv output
    value: ${{ toJSON(steps.uv.outputs) }}
  hatch:
    description: setup hatch output
    value: ${{ toJSON(steps.hatch.outputs) }}
runs:
  using: composite
  steps:
    - id: uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "0.11.11"
        enable-cache: ${{ inputs.cache }}
    - run: echo "HATCH_ENV_TYPE_VIRTUAL_UV_PATH=$(which uv | tr -d '\n')" >> "$GITHUB_ENV"
      shell: bash
    - id: hatch
      uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
      with:
        version: "1.16.5"
