[tools]
python = "3.14.5"
"pipx:hatch" = { version = "1.16.5", uvx_args = "--with pip" }
uv = "0.11.17"

[env]
HATCH_ENV_TYPE_VIRTUAL_UV_PATH = { tools = true, value = "{{ exec(command=mise_bin ~ ' which uv') }}" }