[tools]
hk = "1.54.1"
pkl = "0.32.1"
shellcheck = "0.11.0"
zizmor = "1.29.0"
"github:kjanat/actionlint" = "1.14.0"
"github:boostsecurityio/poutine" = "1.1.6"

[tasks]
pre-commit = { run = "hk run pre-commit" }
