[tools]
python = "3.14.6"
"pipx:hatch" = { version = "1.17.1", uvx_args = "--with pip" }
uv = "0.11.28"

[env]
HATCH_ENV_TYPE_VIRTUAL_UV_PATH = { tools = true, value = "{% if os_family() == 'unix' %}{{ [tools.uv.path, exec(command='ls \"' ~ tools.uv.path ~ '\"') | trim, 'uv'] | join(sep='/') }}{% else %}{{ [tools.uv.path, 'uv.exe'] | join(sep='\\') }}{% endif %}" }
PIP_UPLOADED_PRIOR_TO = "P3D"
UV_EXCLUDE_NEWER = "3 days"
