on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

defaults:
  run:
    working-directory: ./gatelogue-types-rs

jobs:
  cargo-upgrade:
    uses: iiiii7d/cargo-msrv-upgrade-workflow/.github/workflows/workflow.yml@main
