name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@8edca31a1a564aa798ae8f3fd3f681f19fd034dc # main
    with:
      working-directory: gatelogue-types-rs
