name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@c93c75569b5c5def7065c7ad5b854c129dd2e39d # main
    with:
      working-directory: gatelogue-types-rs
