name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@86d36d7f38bec6c1b9b23a4f7528938c9755e8e3 # main
    with:
      working-directory: gatelogue-types-rs
