on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  cargo-upgrade:
    uses: iiiii7d/cargo-msrv-upgrade-workflow/.github/workflows/workflow.yml@main
    defaults:
      run:
        working-directory: ./gatelogue-types-rs