name: Copy SQL, Format, Lint
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # renovate: datasource=custom.rust.nightly depName=x86_64-unknown-linux-gnu versioning=rust-release-channel
  RUST_VERSION: nightly-2026-03-26

jobs:
  copy-sql:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: gatelogue-types-sql/copy.sh
      - run: echo "message=copy sql @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          default_author: github_actions
          message: ${{ env.message }}

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: copy-sql

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
        with:
          version: "1.16.5"
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ env.RUST_VERSION }}
          cache-workspaces: './gatelogue-types-rs -> target'
          components: rustfmt
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: "10.32.1"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.8.1
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - run: cd gatelogue-aggregator && hatch fmt -f
      - run: cd gatelogue-types-py && hatch fmt -f

      - run: cd gatelogue-types-rs && cargo fmt

      - run: cd gatelogue-client && pnpm i && pnpm format
      - run: cd gatelogue-types-ts && pnpm i && pnpm format

      - run: echo "message=format @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          default_author: github_actions
          message: ${{ env.message }}

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: format

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
        with:
          version: "1.16.5"
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ env.RUST_VERSION }}
          cache-workspaces: './gatelogue-types-rs -> target'
          components: clippy
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: "10.32.1"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.8.1
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - run: cd gatelogue-aggregator && hatch fmt && hatch run types:check
      - run: cd gatelogue-types-py && hatch fmt && hatch run types:check
        if: '!cancelled()'

      - run: cd gatelogue-types-rs && cargo clippy --fix --broken-code --allow-dirty
        if: '!cancelled()'

      - run: cd gatelogue-client && pnpm i && pnpm run-s lint:fix type-check
        if: '!cancelled()'
      - run: cd gatelogue-types-ts && pnpm i && pnpm run-s lint:fix type-check
        if: '!cancelled()'

      - run: echo "message=lint @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
        if: github.event_name != 'pull_request' && !cancelled()
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        if: github.event_name != 'pull_request' && !cancelled()
        with:
          commit-message: ${{ env.message }}
          branch: lint
          title: Linting
      - run: git status
        if: github.event_name == 'pull_request' && !cancelled()
        
