name: Format, Lint
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-rust
        with:
          components: rustfmt
      - uses: ./.github/actions/setup-node

      - run: gatelogue-types-sql/copy.sh

      - run: cd gatelogue-aggregator && hatch fmt -f
      - run: cd gatelogue-types-py && hatch fmt -f

      - run: cd gatelogue-types-rs && cargo fmt

      - run: cd gatelogue-client && pnpm i && pnpm format
      - run: cd gatelogue-types-ts && pnpm i && pnpm format

      - run: echo "message=format @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
        if: github.event_name != 'pull_request'
      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        if: github.event_name != 'pull_request'
        with:
          default_author: github_actions
          message: ${{ env.message }}
      - run: git status
        if: github.event_name == 'pull_request'

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      actions: write
    needs: format

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-rust
        with:
          components: clippy
      - uses: ./.github/actions/setup-node
      - uses: cargo-bins/cargo-binstall@d8b2727b3a60691310e57c65e989cb974c787690 # main
      - run: cargo binstall --force clippy-sarif@${{ env.CLIPPY_SARIF_VERSION }}
        env:
          # renovate: datasource=crate depName=clippy-sarif versioning=loose
          CLIPPY_SARIF_VERSION: 0.8.0

      - uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3

      - run: |
          cd gatelogue-aggregator
          hatch fmt -l -- --output-format=sarif | tee ${{ runner.temp }}/aggregator.sarif
          hatch run types:check
        if: '!cancelled()'
      - run: |
          cd gatelogue-types-py
          hatch fmt -l -- --output-format=sarif | tee ${{ runner.temp }}/types-py.sarif
          hatch run types:check
        if: '!cancelled()'

      - run: |
          mkdir sarif-cargo
          cd gatelogue-types-rs
          cargo clippy --locked --fix --broken-code --allow-dirty \
                       --all-targets --all-features --message-format=json |
          clippy-sarif | tee ${{ runner.temp }}/types-rs.sarif
        if: '!cancelled()'

      - run: mkdir sarif-eslint
      - run: |
          cd gatelogue-client
          pnpm i
          pnpm run lint:sarif | tail -n +4 | tee ${{ runner.temp }}/client.sarif
          pnpm run type-check
        if: '!cancelled()'
      - run: |
          cd gatelogue-types-ts
          pnpm i
          pnpm run lint:sarif | tail -n +4 | tee ${{ runner.temp }}/types-ts.sarif
          pnpm run type-check
        if: '!cancelled()'

      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: '!cancelled()'
        with:
          sarif_file: ${{ runner.temp }}/aggregator.sarif
          category: ruff-aggregator
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: '!cancelled()'
        with:
          sarif_file: ${{ runner.temp }}/types-py.sarif
          category: ruff-types-py
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: '!cancelled()'
        with:
          sarif_file: ${{ runner.temp }}/types-rs.sarif
          category: cargo-types-rs
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: '!cancelled()'
        with:
          sarif_file: ${{ runner.temp }}/client.sarif
          category: eslint-client
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: '!cancelled()'
        with:
          sarif_file: ${{ runner.temp }}/types-ts.sarif
          category: eslint-types-ts

      - run: echo "message=lint @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
        if: github.ref_name == 'main' && !cancelled()
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: github.ref_name == 'main' && !cancelled()
        with:
          commit-message: ${{ env.message }}
          branch: lint
          title: Linting
      - run: git status
        if: github.ref_name != 'main' && !cancelled()
        
