name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["**"]
  pull_request:
  
jobs:
  test-types-py:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-py
    permissions:
      contents: read
  
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
        with:
          version: "1.16.5"
      - run: hatch test --all --parallel

  test-types-rs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-rs
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        env:
          # renovate: datasource=custom.rust.nightly depName=x86_64-unknown-linux-gnu versioning=rust-release-channel
          RUST_VERSION: nightly-2026-03-28
        with:
          toolchain: ${{ env.RUST_VERSION }}
          cache-workspaces: './gatelogue-types-rs -> target'

      - run: cargo test --all --all-features

  test-types-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-ts
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: "10.33.0"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.8.1
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - uses: actions/cache@v5
        with:
          path: |
            ~/.local/share/pnpm
            **/node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i
      - run: pnpm test
