name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  test-types-py:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-py
    permissions:
      contents: read
  
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pypa/hatch@install
        with:
          version: "1.16.5"
      - run: hatch test --all --parallel

  test-types-rs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-rs
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: './gatelogue-types-rs -> target'

      - run: cargo test --all --all-features

  test-types-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-ts
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: "10.32.1"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.8.1
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm i
      - run: pnpm test
