name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test-types-py:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-py
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/mise
        with:
          envs: "py"

      - run: hatch test --all --parallel

  test-types-rs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-rs
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/mise
        with:
          envs: "rs"

      - run: cargo test --locked --all --all-targets --all-features

  test-types-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gatelogue-types-ts
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/mise
        with:
          envs: "node"

      - run: pnpm i
      - run: pnpm test
