on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/hatch@install
- run: sudo apt-get update; sudo apt-get install --no-install-recommends graphviz graphviz-dev
      - run: bash update.sh
      - run: git push